services:
  twitter-scraping-selenium:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    image: twitter-scraper-selenium:latest
    env_file:
      - .env

    volumes:
      - ./data:/src/data
    
    depends_on:
      - selenium-chrome

  linkedin-scraping_service:
    build: 
      context: .
      dockerfile: Dockerfile.linkedin
    image: linkedin-scraper:latest
    env_file:
      - .env

    volumes:
      - ./data:/src/data
    
    depends_on:
      - selenium-chrome
      
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"

  new-post-publish-service:
    build:
      context: .
      dockerfile: Dockerfile.new_post
    image: new-post-publish:latest
    env_file:
      - .env


  twitter-scraping-nodriver:
    build: 
      context: .
      dockerfile: Dockerfile.nodriver
    image: twitter-scraper-nodriver:latest
    shm_size: "2gb"
    environment:
      - DISPLAY=:99
    volumes:
      - ./artifacts:/src/artifacts
      - ./data:/src/data
    env_file:
      - .env
    # Security options for Chrome in Docker
    security_opt:
      - seccomp:unconfined
    # Add capabilities needed by Chrome
    cap_add:
      - SYS_ADMIN