FROM python:3.11-slim

WORKDIR /src

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1

# Install system dependencies
RUN apt-get update && apt-get install -y 

COPY requirements.txt .

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy src content to /src folder in container
COPY . .

ENV PYTHONPATH ="${PYTHONPATH}:/src"

CMD [ "python3", "-m", "scraping.twitter.sign_in_by_selenium"]